#include <asbind20/asbind.hpp>
#include <asbind20/io/formatter.hpp>
#include <asbind_test/framework.hpp>

TEST(Stringify, asEContextStateToString)
{
    using namespace asbind20;

    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asEXECUTION_FINISHED), "asEXECUTION_FINISHED");
    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asEXECUTION_SUSPENDED), "asEXECUTION_SUSPENDED");
    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asEXECUTION_ABORTED), "asEXECUTION_ABORTED");
    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asEXECUTION_EXCEPTION), "asEXECUTION_EXCEPTION");
    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asEXECUTION_PREPARED), "asEXECUTION_PREPARED");
    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asEXECUTION_UNINITIALIZED), "asEXECUTION_UNINITIALIZED");
    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asEXECUTION_ACTIVE), "asEXECUTION_ACTIVE");
    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asEXECUTION_ERROR), "asEXECUTION_ERROR");
    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asEXECUTION_DESERIALIZATION), "asEXECUTION_DESERIALIZATION");

    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asEContextState(-1)), "asEContextState(-1)");
    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asEContextState(-2)), "asEContextState(-2)");
}

TEST(Stringify, asERetCodesToString)
{
    using namespace asbind20;

    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asSUCCESS), "asSUCCESS");
    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asERROR), "asERROR");
    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asCONTEXT_ACTIVE), "asCONTEXT_ACTIVE");
    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asCONTEXT_NOT_FINISHED), "asCONTEXT_NOT_FINISHED");
    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asCONTEXT_NOT_PREPARED), "asCONTEXT_NOT_PREPARED");
    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asINVALID_ARG), "asINVALID_ARG");
    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asNO_FUNCTION), "asNO_FUNCTION");
    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asNOT_SUPPORTED), "asNOT_SUPPORTED");
    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asINVALID_NAME), "asINVALID_NAME");
    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asNAME_TAKEN), "asNAME_TAKEN");
    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asINVALID_DECLARATION), "asINVALID_DECLARATION");
    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asINVALID_OBJECT), "asINVALID_OBJECT");
    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asINVALID_TYPE), "asINVALID_TYPE");
    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asALREADY_REGISTERED), "asALREADY_REGISTERED");
    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asMULTIPLE_FUNCTIONS), "asMULTIPLE_FUNCTIONS");
    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asNO_MODULE), "asNO_MODULE");
    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asNO_GLOBAL_VAR), "asNO_GLOBAL_VAR");
    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asINVALID_CONFIGURATION), "asINVALID_CONFIGURATION");
    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asINVALID_INTERFACE), "asINVALID_INTERFACE");
    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asCANT_BIND_ALL_FUNCTIONS), "asCANT_BIND_ALL_FUNCTIONS");
    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asLOWER_ARRAY_DIMENSION_NOT_REGISTERED), "asLOWER_ARRAY_DIMENSION_NOT_REGISTERED");
    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asWRONG_CONFIG_GROUP), "asWRONG_CONFIG_GROUP");
    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asCONFIG_GROUP_IS_IN_USE), "asCONFIG_GROUP_IS_IN_USE");
    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asILLEGAL_BEHAVIOUR_FOR_TYPE), "asILLEGAL_BEHAVIOUR_FOR_TYPE");
    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asWRONG_CALLING_CONV), "asWRONG_CALLING_CONV");
    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asBUILD_IN_PROGRESS), "asBUILD_IN_PROGRESS");
    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asINIT_GLOBAL_VARS_FAILED), "asINIT_GLOBAL_VARS_FAILED");
    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asOUT_OF_MEMORY), "asOUT_OF_MEMORY");
    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asMODULE_IS_IN_USE), "asMODULE_IS_IN_USE");

    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asERetCodes(1)), "asERetCodes(1)");
    EXPECT_EQ(to_string(AS_NAMESPACE_QUALIFIER asERetCodes(2)), "asERetCodes(2)");
}

#ifdef ASBIND20_HAS_LIB_FORMAT

TEST(Stringify, Formatter)
{
    EXPECT_EQ(
        std::format("{}", AS_NAMESPACE_QUALIFIER asALREADY_REGISTERED),
        "asALREADY_REGISTERED"
    );
    EXPECT_EQ(
        std::format("{}", AS_NAMESPACE_QUALIFIER asERetCodes(1)),
        "asERetCodes(1)"
    );

    EXPECT_EQ(
        std::format("{}", AS_NAMESPACE_QUALIFIER asEXECUTION_FINISHED),
        "asEXECUTION_FINISHED"
    );
    EXPECT_EQ(
        std::format("{}", AS_NAMESPACE_QUALIFIER asEContextState(-1)),
        "asEContextState(-1)"
    );
}

#endif
